### ISSUE TITLE
How to make column width be a certain value and can not be slided?

### ISSUE THREAD

**Issue by Mil0R** [Viacheslav-Radchenko/TSTableView#5]
also, can I hide the sliding column border?

**Comment by Viacheslav-Radchenko** [comment]
Hi,

Your data source should return single value in these methods implementation (min==max)
- (CGFloat)minimalWidthForColumnAtIndex:(NSInteger)index;
- (CGFloat)maximalWidthForColumnAtIndex:(NSInteger)index;
- (CGFloat)defaultWidthForColumnAtIndex:(NSInteger)index;

if you’re using default TSDataModel you can set these values when describing column
“defWidth” : @100,
“minWidth” : @100,
“maxWidth” : @100

Regarding sliding column border, this is just a background image, you can check implementation in TSTableViewModel.m
- (TSTableViewHeaderSectionView *)tableView:(TSTableView *)tableView headerSectionViewForColumnAtPath:(NSIndexPath *)indexPath {
  …
  section.backgroundImageView.image = [self headerSectionBackgroundImageWithTintColor:column.color];
  …

And you probably would want to disable highlighting on tap
@property (nonatomic, assign) BOOL highlightControlsOnTap; // property in TSTableView.h

**Comment by Mil0R** [comment]
it works and thanks a lot.
